import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/shadcn/lib/utils";
import localFont from "next/font/local";
import { ThemeProvider } from "next-themes";

const pretendard = localFont({
  src: "./fonts/pretendard/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        pretendard.className,
        "h-full antialiased", //
      )}
    >
      <body className="flex min-h-full flex-col">
        <ThemeProvider attribute="class">{children}</ThemeProvider>
      </body>
    </html>
  );
}
